"""Map English country names (and 2-letter codes) to regional-indicator flag emojis."""

from __future__ import annotations


def iso2_letters_to_flag(iso2: str) -> str:
    """Convert ISO 3166-1 alpha-2 (e.g. FR) to 🇫🇷."""
    code = (iso2 or "").strip().upper()
    if len(code) != 2 or not code.isalpha():
        return ""
    a, b = code
    return chr(ord(a) - ord("A") + 0x1F1E6) + chr(ord(b) - ord("A") + 0x1F1E6)


# Lowercased English names and common aliases → ISO alpha-2
_NAME_TO_ISO2: dict[str, str] = {
    "andorra": "AD",
    "argentina": "AR",
    "armenia": "AM",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahamas": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belgium": "BE",
    "belize": "BZ",
    "bhutan": "BT",
    "bolivia": "BO",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "brazil": "BR",
    "brunei": "BN",
    "bulgaria": "BG",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "chile": "CL",
    "china": "CN",
    "colombia": "CO",
    "costa rica": "CR",
    "croatia": "HR",
    "cuba": "CU",
    "cyprus": "CY",
    "czech republic": "CZ",
    "czechia": "CZ",
    "denmark": "DK",
    "dominican republic": "DO",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "estonia": "EE",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "ethiopia": "ET",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "georgia": "GE",
    "germany": "DE",
    "ghana": "GH",
    "greece": "GR",
    "guatemala": "GT",
    "honduras": "HN",
    "hong kong": "HK",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "jamaica": "JM",
    "japan": "JP",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kuwait": "KW",
    "laos": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "macau": "MO",
    "macao": "MO",
    "madagascar": "MG",
    "malaysia": "MY",
    "maldives": "MV",
    "malta": "MT",
    "mauritius": "MU",
    "mexico": "MX",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "morocco": "MA",
    "mozambique": "MZ",
    "myanmar": "MM",
    "burma": "MM",
    "namibia": "NA",
    "nepal": "NP",
    "netherlands": "NL",
    "holland": "NL",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "nigeria": "NG",
    "north macedonia": "MK",
    "macedonia": "MK",
    "norway": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "panama": "PA",
    "paraguay": "PY",
    "peru": "PE",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "qatar": "QA",
    "romania": "RO",
    "russia": "RU",
    "russian federation": "RU",
    "rwanda": "RW",
    "san marino": "SM",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "singapore": "SG",
    "slovakia": "SK",
    "slovenia": "SI",
    "south africa": "ZA",
    "south korea": "KR",
    "korea": "KR",
    "republic of korea": "KR",
    "spain": "ES",
    "sri lanka": "LK",
    "sweden": "SE",
    "switzerland": "CH",
    "taiwan": "TW",
    "tanzania": "TZ",
    "thailand": "TH",
    "tunisia": "TN",
    "turkey": "TR",
    "türkiye": "TR",
    "turkiye": "TR",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "uae": "AE",
    "dubai": "AE",
    "united kingdom": "GB",
    "uk": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "northern ireland": "GB",
    "united states": "US",
    "usa": "US",
    "u.s.a.": "US",
    "u.s.": "US",
    "america": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "venezuela": "VE",
    "vietnam": "VN",
    "viet nam": "VN",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    "bermuda": "BM",
    "bermuda (uk)": "BM",
    "puerto rico": "PR",
    "us virgin islands": "VI",
    "british virgin islands": "VG",
    "aruba": "AW",
    "curacao": "CW",
    "curaçao": "CW",
    "bonaire": "BQ",
    "sint maarten": "SX",
    "saint martin": "MF",
    "guadeloupe": "GP",
    "martinique": "MQ",
    "réunion": "RE",
    "reunion": "RE",
    "new caledonia": "NC",
    "french polynesia": "PF",
    "cook islands": "CK",
    "palau": "PW",
    "marshall islands": "MH",
    "micronesia": "FM",
    "solomon islands": "SB",
    "vanuatu": "VU",
    "papua new guinea": "PG",
    "tonga": "TO",
    "samoa": "WS",
    "american samoa": "AS",
    "guam": "GU",
    "northern mariana islands": "MP",
    "greenland": "GL",
    "faroe islands": "FO",
    "isle of man": "IM",
    "jersey": "JE",
    "guernsey": "GG",
    "gibraltar": "GI",
    "albania": "AL",
    "algeria": "DZ",
    "angola": "AO",
    "belarus": "BY",
    "benin": "BJ",
    "bosnia": "BA",
    "burkina faso": "BF",
    "burundi": "BI",
    "cape verde": "CV",
    "chad": "TD",
    "congo": "CG",
    "democratic republic of the congo": "CD",
    "drc": "CD",
    "ivory coast": "CI",
    "côte d'ivoire": "CI",
    "cote d'ivoire": "CI",
    "djibouti": "DJ",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "gabon": "GA",
    "gambia": "GM",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "iran": "IR",
    "iraq": "IQ",
    "liberia": "LR",
    "libya": "LY",
    "mali": "ML",
    "mauritania": "MR",
    "moldova": "MD",
    "niger": "NE",
    "north korea": "KP",
    "palestine": "PS",
    "sao tome and principe": "ST",
    "sierra leone": "SL",
    "somalia": "SO",
    "south sudan": "SS",
    "sudan": "SD",
    "suriname": "SR",
    "syria": "SY",
    "togo": "TG",
    "trinidad and tobago": "TT",
    "yemen": "YE",
    "afghanistan": "AF",
    "vatican": "VA",
    "vatican city": "VA",
}


def _normalize_country_key(name: str) -> str:
    s = (name or "").strip().lower()
    if s.startswith("the "):
        s = s[4:].strip()
    if "(" in s:
        s = s.split("(", 1)[0].strip()
    return s


def flag_emoji_for_country(country: str) -> str:
    """Return a flag emoji for a country name, or empty if unknown."""
    key = _normalize_country_key(country)
    if not key:
        return ""
    iso = _NAME_TO_ISO2.get(key)
    if iso:
        return iso2_letters_to_flag(iso)
    # Single-token match (e.g. "Thailand" already exact)
    for part in key.replace(",", " ").split():
        iso = _NAME_TO_ISO2.get(part.strip())
        if iso:
            return iso2_letters_to_flag(iso)
    return ""


def resolve_destination_flag(flag_emoji: str | None, country: str) -> str:
    """
    Prefer the model's flag when it looks real; otherwise derive from country.
    Accepts bare ISO2 (e.g. FR) as flag_emoji.
    """
    raw = (flag_emoji or "").strip()
    if raw and raw != "🌍":
        if len(raw) == 2 and raw.isalpha():
            conv = iso2_letters_to_flag(raw.upper())
            return conv or raw
        return raw
    resolved = flag_emoji_for_country(country)
    return resolved or "🌍"
